
# JdbcTemplate y DAO Support

## Uso de templates con Spring

TIP: Un método de un template define el esqueleto de un proceso.
El proceso por si mísmo es fijo, nunca cambia. Algunos pasos del proceso son fijos también, algunos pasos pasan cada vez que se ejecuta un proceso. En algunos puntos, el proceso delega el trabajo a una subclase para llenarlo con algunas implementaciones con detalles muy específicos, es decir, es la parte variable del proceso.

En términos de software, un método de un template delega porciones específicas de una implementación del proceso a una interface. Diferentes implementaciones de esta interface definen implementaciones específicas de esta porción del proceso. Este es el mismo patrón que Spring aplica al acceso a datos. Sin importar la tecnología ciertos pasos del acceso a datos son requeridos. Por ejemplo, siempre necesitamos obtener una conexión al DataSource y liberar recursos cuando ha terminado, pero cada método de acceso a datos que escribimos es ligeramente doferente. Buscamos por diferentes objetos y actualizamos en diferentes maneras.

Spring separa las partes fijas y las variables del proceso de acceso a datos en dos distintas clases: _templates_ y _callbacks_. Los templates administran la parte fija del proceso mientras que el código de acceso de datos personalizados se maneja en los _callbacks_.

En un template del DAO:

* Se preparan los recursos
* Se comienza la transacción
* ….
* Se hace commit/rollback de la transacción
* Se cierran recursos y se manejan errores

En un callback del DAO:
* ….
* Se ejecuta una transacción
* Se regresan los datos y se tratan
* …

### Templates de acceso a datos
Springframework viene con varios templates de acceso a datos, cada uno adecuado para un mecanismo de persistencia diferente. Los más comúnes precedidos por el nombre de paquete `org.springframework`:

* JDBC
** `jdbc.core.JdbcTemplate`
** `jdbc.core.namedparam.NameParameterJdbcTemplate`
** `jdbc.core.simple.SimpleJdbcTemplate`
* Hibernate
** `orm.hibernate.HibernateTemplate`
** `orm.hibernate3.HibernateTemplate`
* JPA
** `orm.jpa.JpaTemplate`
** `iBatis`
** `orm.ibatis.SqlMapClientTemplate`

### Usando el JdbcTemplate
La clase `JdbcTemplate` es central en el paquete de JDBC. Maneja la creación y liberación de recursos, los cuales ayudan a evitar errores comúnes como el cerrado de las conexiones. Actúa tareas básicas del flujo de JDBC como la creación de sentencias y su ejecución, dejando al código de la aplicación proveer el SQL y extraer los resultados.

La clase `JdbcTemplate` ejecuta consultas, sentencias de actualización y llamadas a procedimientos almacenados, realiza las iteraciones sobre el `ResultSet` y la extracción de los valores de los parámetros. Además atrapa las excepciones JDBC y las traduce a una jerarquía de excepciones más informativa definidas por Spring.

TIP: Lo único que necesita un `JdbcTemplate` es un `DataSource`, y tiene varios métodos de conveniencia que ayudan a realizar operaciones de base de datos de una forma muy simple. El DataSource siempre debe ser configurado como un bean en el contenedor de Spring.

*JdbcTemplateConfig.javai*
[source,java]
----
package com.makingdevs.practica2;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportResource;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
@ImportResource(value={"classpath:/com/makingdevs/practica1/DataSourceWithNamespace.xml"})
public class JdbcTemplateConfig {

  @Autowired
  DataSource dataSource;

  @Bean
  public JdbcTemplate jdbcTemplate(){
    return new JdbcTemplate(dataSource);
  }
}
----

*UsingJdbcTemplateTests.java*
[source,java]
----
package com.makingdevs.practica2;

import static org.junit.Assert.assertEquals;

import java.util.Date;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { JdbcTemplateConfig.class })
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class UsingJdbcTemplateTests {

  @Autowired
  JdbcTemplate jdbcTemplate;

  @Test
  public void test1CountWithJdbcTemplate() {
    int rowCount = jdbcTemplate.queryForObject("SELECT count(*) FROM user", Integer.class);
    assertEquals(7, rowCount);
  }

  @Test
  public void test2CountBindingVariableWithJdbcTemplate() {
    int rowCount = jdbcTemplate.queryForObject("SELECT count(*) FROM user WHERE username = ?", Integer.class,
        "makingdevs");
    assertEquals(1, rowCount);
  }

  @Test
  public void test3QueryStringWithJdbcTemplate() {
    String projectName = jdbcTemplate.queryForObject("SELECT code_name FROM project WHERE id = ?", new Object[] { 4L },
        String.class);
    assertEquals("AGILE-TASKBOARD", projectName);
  }

  @Test
  public void test4InsertWithJdbcTemplate() {
    int rowCount = jdbcTemplate.update(
        "INSERT INTO project(CODE_NAME,DESCRIPTION,NAME,DATE_CREATED,LAST_UPDATED) values(?,?,?,?,?)", "PROJECT",
        "This is a new project", "New project", new Date(), new Date());
    assertEquals(1, rowCount); // Why this is 1?
    String projectDescription = jdbcTemplate.queryForObject("SELECT description FROM project WHERE CODE_NAME = ?", new Object[] { "PROJECT" },
        String.class);
    assertEquals(projectDescription, "This is a new project");
  }

  @Test
  public void test5UpdateWithJdbcTemplate() {
    int rowCount = jdbcTemplate.update(
        "UPDATE project SET DESCRIPTION = ?,NAME = ?,LAST_UPDATED = ? WHERE CODE_NAME = ?", "The project is updated",
        "Project Updated", new Date(), "PROJECT");
    assertEquals(1, rowCount);
  }

  @Test(expected=DataAccessException.class)
  public void test6DeleteWithJdbcTemplate() {
    int rowCount = jdbcTemplate.update(
        "DELETE FROM project WHERE CODE_NAME = ?", "PROJECT");
    assertEquals(1, rowCount);
    String projectDescription = jdbcTemplate.queryForObject("SELECT description FROM project WHERE CODE_NAME = ?", new Object[] { "PROJECT" },
        String.class);
  }

  @Test
  public void test7CreateTempTableWithJdbcTemplate(){
    jdbcTemplate.execute("CREATE TABLE TEMP(ID INTEGER, NAME VARCHAR(100))");
  }

}
----

TIP: Te recomendamos explorar la link:http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html[documentación del JdbcTemplate] para que puedas determinar las diferencias entre los métodos execute y update.

Las instancias de `JdbcTemplate` son threadsafe una vez que son configuradas. Esto es importante por que significa que podemos configurar una sola instancia e inyectar la refencia compartida de forma segura referenciandola en múltiples componentes(DAO).

El `JdbcTemplate` es stateful, en lo que mantiene la referencia al `DataSource`, pero este estado no es conversacional.

NOTE: `NamedParameterJdbcTemplate`

La clase `NamedParameterJdbcTemplate` agrega el soporte para la programación de sentencias JDBC usando parámetros nombrados, en lugar de los marcadores “?”. Lo que hace es rodear al `JdbcTemplate` para después delegar el trabajo.

*NamedJdbcTemplateAppCtx.xml*
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

  <bean class="org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate">
    <constructor-arg ref="dataSource"/>
  </bean>

</beans>
----

*UsingNamedJdbcTemplateTests.java*
[source,java]
----
package com.makingdevs.practica2;

import static org.junit.Assert.assertEquals;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations={"NamedJdbcTemplateAppCtx.xml","../practica1/DataSourceWithNamespace.xml"})
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class UsingNamedJdbcTemplateTests {

  @Autowired
  NamedParameterJdbcTemplate jdbcTemplate;

  @Test
  public void test1CountWithJdbcTemplate() {
    // Easy way!
    Map<String,Object> namedParameters = new HashMap<String,Object>();
    int rowCount = jdbcTemplate.queryForObject("SELECT count(*) FROM user", namedParameters, Integer.class);
    assertEquals(7, rowCount);
  }

  @Test
  public void test2CountBindingVariableWithJdbcTemplate() {
    String sql = "SELECT count(*) FROM user WHERE username = :username";
    // Using Spring parameters
    SqlParameterSource namedParameters = new MapSqlParameterSource("username", "makingdevs");
    int rowCount = jdbcTemplate.queryForObject(sql, namedParameters, Integer.class);
    assertEquals(1, rowCount);
  }

  @Test
  public void test3QueryStringWithJdbcTemplate() {
    String sql = "SELECT code_name FROM project WHERE id = :id";
    Map<String, String> namedParameters = Collections.singletonMap("id", "4");
    String projectName = jdbcTemplate.queryForObject(sql, namedParameters, String.class);
    assertEquals("AGILE-TASKBOARD", projectName);
  }

  // Hey!!! check the BeanPropertySqlParameterSource class

}
----

TIP: Aunque la clase `JdbcTemplate` es muy poderosa y podría usarse de forma independiente, te recomendamos ampliamente que la uses con el soporte a DAO's que ofrece Spring.

## El JdbcTemplate y los RowMappers
La interfaz `RowMapper` es usada por el `JdbcTemplate` para mapear las filas de un `ResultSet` fila por fila. Las implementaciones de esta interfaz realizan el trabajo actual de mapear cada fila en un objeto resultado, pero no necesitan preocuparse acerca del manejo de excepiones. Todo lo que sea `SQLException` será cachao y manejado por `JdbcTemplate`.

Los RowMappers son típicamente _stateless_ y por lo tanto pueden reusarse, son ideales para implementar lógica de mapeo por fila en un solo lugar.

*ProjectMapper.java*
[source,java]
----
package com.makingdevs.practica3;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.makingdevs.model.Project;

public class ProjectMapper implements RowMapper<Project> {

  @Override
  public Project mapRow(ResultSet rs, int rowNum) throws SQLException {
    Project project = new Project();
    project.setId(rs.getLong("id"));
    project.setName(rs.getString("name"));
    project.setCodeName(rs.getString("code_name"));
    project.setDescription(rs.getString("description"));
    project.setDateCreated(rs.getDate("date_created"));
    project.setLastUpdated(rs.getDate("last_updated"));
    return project;
  }

}
----

*NamedJdbcTemplateAppCtx.java*
[source,java]
----
package com.makingdevs.practica3;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import static org.springframework.util.Assert.*;

import com.makingdevs.model.Project;
import com.makingdevs.practica2.JdbcTemplateConfig;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { JdbcTemplateConfig.class })
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ProjectRowMapperTests {

  @Autowired
  JdbcTemplate jdbcTemplate;

  @Test
  public void testQueryWithMapper() {
    String sql = "SELECT * FROM project";
    List<Project> projects = jdbcTemplate.query(sql, new ProjectMapper());
    assertEquals(projects.size(), 4);
    for (Project p : projects) {
      assertEquals(p.getClass(), Project.class);
      isTrue(p.getId() > 0);
    }
  }
}
----

TIP: Te recomendamos consultar la link:http://docs.spring.io/spring/docs/4.0.1.RELEASE/javadoc-api/org/springframework/jdbc/core/RowMapper.html[documentación de la interfaz RowMapper] para que puedas ver que tipos de tratamiento le puedes dar a tu ResultSet y los valores que podrías regresar.

## Soporte a DAO’s
El soporte de DAO de Spring apunta a hacer mucho más fácil el trabajo con las tecnologías de acceso a datos como JDBC, Hibernate, JPA o JDO en una forma consistente. Esto permite cambiar entre las tecnologías de persistencia fácilmente y además permite codificar sin preocuparse por cachar excepciones que sean específicas de cierta tecnología.

TIP: La jerarquía de excepciones de accesso a datos en Spring es clave con ayuda de `DataAccessException`.

La mejor manera de garantizar que tus DAO’s o repositorios provean de la traducción de excepciones es usando la anotación `@Repository`. Esta anotación permite el soporte de escaneo de componentes para encontrar y configurar _repositories_ sin el XML.

Caulquier implementación de DAO o repositorio necesitará acceder a un recurso de persistencia, dependiendo de la tecnología de persistencia usada. Y puedes usar cualquier forma de Inyección de Dependencias que conozcas para hacerlo.

*TaskDaoJpaImpl.java*
[source,java]
----
// Until Spring 3
// Check this out! http://docs.spring.io/spring/docs/3.1.4.RELEASE/javadoc-api/org/springframework/dao/support/DaoSupport.html
@Repository
public class TaskDaoJpaImpl extends JpaDaoSupport implements TaskDao {

  // @Autowired
  @PersistenceContext
  private EntityManager entityManager;

  // Über code !!!

}
----

*TaskDaoHibernate3Impl.java*
[source,java]
----
@Repository
public class TaskDaoHibernate3Impl extends HibernateDaoSupport implements TaskDao {

  private SessionFactory sessionFactory;

  @Autowired
  public void setSessionFactory(SessionFactory sessionFactory) {
    this.sessionFactory = sessionFactory;
  }

    // Über code !!!

}
----

*TaskDaoJdbcImpl.javai*

[source,java]
----
@Repository
public class TaskDaoJdbcImpl extends JdbcDaoSupport implements TaskDao {

  private JdbcTemplate jdbcTemplate;

  @Autowired
  public void init(DataSource dataSource) {
    this.jdbcTemplate = new JdbcTemplate(dataSource);
  }

  // Über code !!!
}
----

## Creando DAO’s con JdbcDaoSupport

*UserStoryMapper.java*
[source,java]
----
package com.makingdevs.practica4;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.makingdevs.model.Project;
import com.makingdevs.model.UserStory;

public class UserStoryMapper implements RowMapper<UserStory> {

  @Override
  public UserStory mapRow(ResultSet rs, int rowNum) throws SQLException {
    UserStory userStory = new UserStory();
    userStory.setId(rs.getLong("ID"));
    userStory.setDateCreated(rs.getDate("DATE_CREATED"));
    userStory.setLastUpdated(rs.getDate("LAST_UPDATED"));
    userStory.setEffort(rs.getInt("EFFORT"));
    userStory.setPriority(rs.getInt("PRIORITY"));
    userStory.setDescription(rs.getString("DESCRIPTION"));
    Project project = new Project();
    project.setId(rs.getLong("PROJECT_ID"));
    userStory.setProject(project);
    return userStory;
  }

}
----

*UserStoryDaoJdbcImplTests.java*
[source,java]
----
package com.makingdevs.practica4;

import static org.springframework.util.Assert.isTrue;

import java.util.List;

import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.makingdevs.dao.UserStoryDao;
import com.makingdevs.model.Project;
import com.makingdevs.model.UserStory;
import static org.springframework.util.Assert.*;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "FirstDaoAppCtx.xml", "../practica1/DataSourceWithNamespace.xml" })
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class UserStoryDaoJdbcImplTests {

  @Autowired
  UserStoryDao userStoryDao;

  private static long userStoryId;

  @Test
  public void test0FindAll() {
    List<UserStory> userStories = userStoryDao.findAll();
    notEmpty(userStories);
  }

  @Test
  public void test1CreateUserStory() {
    UserStory us = new UserStory();
    us.setEffort(3);
    us.setPriority(1);
    us.setDescription("As user... I want... In order to...");
    Project p = new Project();
    p.setId(1L);
    us.setProject(p);
    userStoryId = userStoryDao.create(us);
    isTrue(userStoryId > 0);
  }

  @Test
  public void test2QueryUserStory() {
    UserStory userStory = userStoryDao.read(userStoryId);
    isTrue(3 == userStory.getEffort());
    isTrue(1 == userStory.getPriority());
    Assert.assertEquals("As user... I want... In order to...", userStory.getDescription());
    Assert.assertNotNull(userStory.getProject());
    isTrue(userStory.getProject().getId() == 1);
  }

  @Test
  public void test3UpdateUserStory() {
    UserStory userStory = userStoryDao.read(userStoryId);
    String oldDescription = userStory.getDescription();
    userStory.setDescription("As admin... I wish... Because...");
    userStory.setEffort(5);
    userStory.setPriority(4);
    userStoryDao.update(userStory);
    UserStory userStoryUpdated = userStoryDao.read(userStoryId);
    isTrue(5 == userStoryUpdated.getEffort());
    isTrue(4 == userStoryUpdated.getPriority());
    Assert.assertEquals("As admin... I wish... Because...", userStoryUpdated.getDescription());
    Assert.assertNotEquals(oldDescription, userStoryUpdated.getDescription());
  }

  @Test(expected = DataAccessException.class)
  public void test4DeleteUserStory() {
    UserStory userStory = userStoryDao.read(userStoryId);
    userStoryDao.delete(userStory);
    userStoryDao.read(userStoryId);
  }

  @Test
  public void test5FindByEffort() {
    List<UserStory> userStories = userStoryDao.findAllByEffortBetween(1, 3);
    for (UserStory us : userStories) {
      isTrue(us.getEffort() >= 1 && us.getEffort() <= 3);
    }
  }
----

*UserStoryMapper.java*
[source,java]
----
package com.makingdevs.practica4;

import java.util.Date;
import java.util.List;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
import org.springframework.stereotype.Repository;

import com.makingdevs.dao.UserStoryDao;
import com.makingdevs.model.Project;
import com.makingdevs.model.UserStory;

@Repository
public class UserStoryDaoJdbcImpl extends JdbcDaoSupport implements UserStoryDao {

  @Autowired
  public UserStoryDaoJdbcImpl(DataSource dataSource){
    super.setDataSource(dataSource);
  }

  private static String sqlQuery = "SELECT * FROM user_story";

  @Override
  public Long create(UserStory newInstance) {
    String sqlInsert = "INSERT INTO user_story(DATE_CREATED,DESCRIPTION,EFFORT,LAST_UPDATED,PRIORITY,PROJECT_ID) "
        + "VALUES(?,?,?,?,?,?);";
    getJdbcTemplate().update(sqlInsert, new Date(), newInstance.getDescription(), newInstance.getEffort(), new Date(),
        newInstance.getPriority(), newInstance.getProject().getId());
    Long userStoryId = getJdbcTemplate().queryForObject(
        "SELECT id FROM user_story WHERE DESCRIPTION = ? AND PROJECT_ID = ?",
        new Object[] { newInstance.getDescription(), newInstance.getProject().getId() }, Long.class);
    return userStoryId;
  }

  @Override
  public UserStory read(Long id) {
    return getJdbcTemplate().queryForObject(sqlQuery + " WHERE ID = ?", new Object[] { id }, new UserStoryMapper());
  }

  @Override
  public void update(UserStory transientObject) {
    String sqlUpdate = "UPDATE user_story SET DESCRIPTION = ?,EFFORT = ?,LAST_UPDATED = ?,PRIORITY = ?,PROJECT_ID = ? WHERE ID = ?";
    getJdbcTemplate().update(sqlUpdate, transientObject.getDescription(), transientObject.getEffort(), new Date(),
        transientObject.getPriority(), transientObject.getProject().getId(), transientObject.getId());
  }

  @Override
  public void delete(UserStory persistentObject) {
    String sqlDelete = "DELETE FROM user_story WHERE ID = ?";
    getJdbcTemplate().update(sqlDelete, persistentObject.getId());
  }

  @Override
  public List<UserStory> findAll() {
    return getJdbcTemplate().query(sqlQuery, new UserStoryMapper());
  }

  @Override
  public int countAll() {
    String countQuery = "SELECT count(*) FROM user_story";
    return getJdbcTemplate().queryForObject(countQuery, Integer.class);
  }

  @Override
  public List<UserStory> findAllByEffortBetween(Integer lowValue, Integer maxValue) {
    String findAllByEffortBetweenSql = sqlQuery + " WHERE EFFORT BETWEEN ? AND ?";
    return getJdbcTemplate().query(findAllByEffortBetweenSql, new Object[] { lowValue, maxValue }, new UserStoryMapper());
  }

  @Override
  public List<UserStory> findAllByPriorityBetween(Integer lowValue, Integer maxValue) {
    String findAllByPriorityBetweenSql = sqlQuery + " WHERE PRIORITY BETWEEN ? AND ?";
    return getJdbcTemplate().query(findAllByPriorityBetweenSql, new Object[] { lowValue, maxValue }, new UserStoryMapper());
  }

  @Override
  public List<UserStory> findAllByProject(Project project) {
    String findByProjectIdSql = "SELECT * FROM user_story us INNER JOIN project p ON p.id = us.project_id WHERE us.project_id = ?";
    return getJdbcTemplate().query(findByProjectIdSql, new Object[] { project.getId() }, new UserStoryMapper());
  }

}
----

*TaskDaoConfig.java*
[source,java]
----
package com.makingdevs.practica5;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportResource;

import com.makingdevs.dao.TaskDao;

@Configuration
@ImportResource(value={"classpath:/com/makingdevs/practica1/DataSourceWithNamespace.xml"})
public class TaskDaoConfig {

  @Autowired
  DataSource dataSource;

  @Bean
  public TaskDao taskDado(){
    return new TaskDaoJdbcImpl(dataSource);
  }
}
----

*TaskMapper.java*
[source,java]
----
package com.makingdevs.practica5;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.makingdevs.model.Task;
import com.makingdevs.model.TaskStatus;
import com.makingdevs.model.UserStory;

public class TaskMapper implements RowMapper<Task> {

  @Override
  public Task mapRow(ResultSet rs, int rowNum) throws SQLException {
    Task task = new Task();
    task.setId(rs.getLong("ID"));
    task.setDateCreated(rs.getDate("DATE_CREATED"));
    task.setDateCreated(rs.getDate("LAST_UPDATED"));
    task.setDescription(rs.getString("DESCRIPTION"));
    task.setStatus(TaskStatus.valueOf(rs.getString("STATUS")));
    UserStory us = new UserStory();
    us.setId(rs.getLong("USER_STORY_ID"));
    task.setUserStory(us);
    return task;
  }

}
----

*TaskDaoJdbcImpl.java*
[source,java]
----
package com.makingdevs.practica5;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.namedparam.BeanPropertySqlParameterSource;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcDaoSupport;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.stereotype.Repository;

import com.makingdevs.dao.TaskDao;
import com.makingdevs.model.Task;
import com.makingdevs.model.TaskStatus;
import com.makingdevs.model.User;
import com.makingdevs.model.UserStory;

@Repository
public class TaskDaoJdbcImpl extends NamedParameterJdbcDaoSupport implements TaskDao {

  @Autowired
  public TaskDaoJdbcImpl(DataSource dataSource) {
    super.setDataSource(dataSource);
  }

  private static String sqlQuery = "SELECT * FROM TASK ";

  @Override
  public Long create(Task newInstance) {
    String sqlInsert = "INSERT INTO TASK(DATE_CREATED,DESCRIPTION,LAST_UPDATED,STATUS,USER_STORY_ID)"
        + " VALUES(:DATE_CREATED,:DESCRIPTION,:LAST_UPDATED,:STATUS,:USER_STORY_ID)";
    Map<String, Object> inputParameters = new HashMap<String, Object>();
    inputParameters.put("DATE_CREATED", new Date());
    inputParameters.put("LAST_UPDATED", new Date());
    inputParameters.put("DESCRIPTION", newInstance.getDescription());
    inputParameters.put("STATUS", TaskStatus.TODO.toString());
    inputParameters.put("USER_STORY_ID", newInstance.getUserStory().getId());
    getNamedParameterJdbcTemplate().update(sqlInsert, inputParameters);
    String sqlForPrimaryKey = "SELECT ID FROM TASK WHERE DESCRIPTION = :DESCRIPTION AND STATUS = :STATUS";
    return getNamedParameterJdbcTemplate().queryForObject(sqlForPrimaryKey, inputParameters, Long.class);
  }

  @Override
  public Task read(Long id) {
    SqlParameterSource namedParameters = new MapSqlParameterSource("id", id);
    return getNamedParameterJdbcTemplate().queryForObject(sqlQuery + "WHERE ID = :id", namedParameters,
        new TaskMapper());
  }

  @Override
  public void update(Task transientObject) {
    String sqlUpdate = "UPDATE TASK SET DESCRIPTION = :description,"
        + "LAST_UPDATED = :lastUpdated,STATUS = :status,USER_STORY_ID = :userStory.id WHERE ID = :id";
    transientObject.setLastUpdated(new Date());
    SqlParameterSource namedParameters = new BeanPropertySqlParameterSource(transientObject);
    getNamedParameterJdbcTemplate().update(sqlUpdate, namedParameters);
  }

  @Override
  public void delete(Task persistentObject) {
    String sqlDelete = "DELETE FROM TASK WHERE ID = ?";
    getJdbcTemplate().update(sqlDelete, persistentObject.getId());
  }

  @Override
  public List<Task> findAll() {
    return getNamedParameterJdbcTemplate().query(sqlQuery, new TaskMapper());
  }

  @Override
  public int countAll() {
    String countSql = "SELECT count(*) FROM task";
    return getJdbcTemplate().queryForObject(countSql, Integer.class);
  }

  @Override
  public List<Task> findAllByDescriptionLike(String description) {
    String sqlFindAllByDescription = sqlQuery + " WHERE DESCRIPTION LIKE :DESCRIPTION";
    SqlParameterSource namedParameters = new MapSqlParameterSource("DESCRIPTION", description);
    return getNamedParameterJdbcTemplate().query(sqlFindAllByDescription, namedParameters, new TaskMapper());
  }

  @Override
  public List<Task> findAllByUserStoryAndStatusEquals(UserStory userStory, TaskStatus taskStatus) {
    // Is your turn SQL expert !!!
    return null;
  }

  @Override
  public List<Task> findAllByUser(User user) {
 // Is your turn!!!!
    return null;
  }
}
----

*TaskDaoJdbcImplTests.java*
[source,java]
----
package com.makingdevs.practica5;

import static org.springframework.util.Assert.isTrue;
import static org.springframework.util.Assert.notEmpty;

import java.util.List;

import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.makingdevs.dao.TaskDao;
import com.makingdevs.model.Task;
import com.makingdevs.model.UserStory;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { TaskDaoConfig.class })
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class TaskDaoJdbcImplTests {

  @Autowired
  TaskDao taskDao;

  private static long taskId;

  @Test
  public void test0FindAll() {
    List<Task> tasks = taskDao.findAll();
    notEmpty(tasks);
  }

  @Test
  public void test1CreateTask() {
    Task task = new Task();
    task.setDescription("A new task");
    UserStory userStory = new UserStory();
    userStory.setId(1L);
    task.setUserStory(userStory);
    taskId = taskDao.create(task);
    isTrue(taskId > 0);
  }

  @Test
  public void test2QueryTask() {
    Task task = taskDao.read(taskId);
    Assert.assertNotNull(task);
    isTrue(task.getDescription().equals("A new task"));
  }

  // Your responsability is to test!!!!

}
----

NOTE: ¡Es tu turno! Implementa los DAO's faltantes, inclusive crea relaciones que puedan poblar varios objetos con una consulta con ayuda del RowMapper.

### Enfoques de acceso a datos disponibles.
Podemos escoger varios enfoques para el acceso a datos con JDBC con `JdbcTemplate`. Una vez que comenzamos a usarlos, podemos mezclarlos para lograr funcionalidad más específica; estos son:

* `JdbcTemplate` - Es el enfoque más popular, el de nivel más bajo.
* `NamedParameterJdbcTemplate` - Rodea un JdbcTemplate para proveer parámetros nombrados en lugar de los marcadores “?”. Este enfoque provee de mejro documentación del uso del template cuando tenemos varios parámetros por aplicar.
* `SimpleJdbcInsert` y `SimpleJdbcCall` - Optimizan los metadatos de la base de datos para límitar la cantidad de configuración necesaria. Este enfoque simplifica el código a escribir de tal manera que sólo hay que proveer el nombre de la tabla o procedimiento, y proveer un mapa de parámteros coincidiendo los nombres de las columnas. Esto sólo funciona si la base de datos provee los metadatos adecuados, en caso contrario, tendremos que ponerlos nosotros mismo en configuración.
* Objetos de RDBMS
** `MappingSqlQuery`
** `SqlUpdate`
** `StoredProcedure`
